# Generated by Django 5.0.1 on 2024-01-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalProjects',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internetionalContact.basemodel')),
                ('project_name', models.CharField(max_length=250)),
                ('partner_organization', models.CharField(max_length=250)),
                ('funding_organization', models.CharField(max_length=250)),
                ('done_undone_year', models.IntegerField()),
                ('project_status', models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('bajarilmagan', 'Bajarilmagan')], default='bajarilmagan', max_length=20)),
                ('image', models.ImageField(upload_to='images/internetionalContact/international_projects')),
            ],
            options={
                'verbose_name': 'International Project',
                'verbose_name_plural': 'International Projects',
            },
            bases=('internetionalContact.basemodel',),
        ),
        migrations.CreateModel(
            name='InternationalResearchers',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internetionalContact.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/internetionalContact/international_researchers')),
            ],
            bases=('internetionalContact.basemodel',),
        ),
        migrations.CreateModel(
            name='InternationalResearchersExpert',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internetionalContact.basemodel')),
                ('full_name', models.CharField(max_length=250)),
                ('activity_institution', models.CharField(max_length=350)),
                ('year_of_visit', models.IntegerField()),
                ('researchers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to='internetionalContact.internationalresearchers')),
            ],
            bases=('internetionalContact.basemodel',),
        ),
    ]
