# Generated by Django 5.0.1 on 2024-01-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConferencesCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meeting.basemodel')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Conferences Category',
                'verbose_name_plural': 'Conferences Category',
            },
            bases=('meeting.basemodel',),
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meeting.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('context', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='meeting.conferencescategory')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
            bases=('meeting.basemodel',),
        ),
        migrations.CreateModel(
            name='ConferencesImg',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meeting.basemodel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('conferences_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences_img', to='meeting.conferences')),
            ],
            bases=('meeting.basemodel',),
        ),
    ]
