# Generated by Django 5.0.1 on 2024-01-24 17:57

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturallegaldocuments',
            name='context',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
