# Generated by Django 5.0.1 on 2024-01-25 09:21

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_institute', '0002_alter_architecturallegaldocuments_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyinstitute',
            name='contex',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='context',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
