# Generated by Django 5.0.1 on 2024-01-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'research', 'verbose_name_plural': 'researches'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'work', 'verbose_name_plural': 'works'},
        ),
    ]
