# Generated by Django 5.0.1 on 2024-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_options_alter_research_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(upload_to='images/department/depart/'),
        ),
    ]
