# Generated by Django 5.0.1 on 2024-01-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_category_options'),
        ('department', '0004_department_context_ru_department_context_uz_and_more'),
    ]

    operations = [
    ]
