<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-20 09:28
=======
# Generated by Django 5.0.1 on 2024-01-20 08:52
>>>>>>> origin/main

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ArchitecturalLegalDocuments',
=======
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
>>>>>>> origin/main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('title', models.CharField(max_length=250)),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name': 'Architectural Legal Document',
                'verbose_name_plural': 'Architectural Legal Documents',
=======
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/department/depart')),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
>>>>>>> origin/main
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='HistoryInstitute',
=======
            name='Employee',
>>>>>>> origin/main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/aboutInstitut/history_institute')),
                ('contex', models.TextField()),
            ],
            options={
                'verbose_name': 'History Institute',
                'verbose_name_plural': 'History Institutes',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('reception_days', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/aboutInstitut/leadership')),
            ],
            options={
                'verbose_name': 'Leadership',
                'verbose_name_plural': 'Leaderships',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
=======
                ('fullname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='images/department/employee/')),
                ('departmentemp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentemp', to='aboutInstitut.department')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Research',
>>>>>>> origin/main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/aboutInstitut/news')),
                ('context', models.TextField()),
            ],
            options={
=======
                ('context', models.TextField()),
                ('departmentres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentres', to='aboutInstitut.department')),
            ],
            options={
                'verbose_name': 'research',
                'verbose_name_plural': 'researches',
>>>>>>> origin/main
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='OrganizationStructure',
=======
            name='Works',
>>>>>>> origin/main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('image', models.ImageField(upload_to='images/aboutInstitut/organization_structure')),
            ],
            options={
                'verbose_name': 'Organization Structure',
                'verbose_name_plural': 'Organization Structures',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryInstituteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('history_institute_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_institute_img', to='aboutInstitut.historyinstitute')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadershipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('leadership_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_img', to='aboutInstitut.leadership')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('news_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_img', to='aboutInstitut.news')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationStructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('organization_structure_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_structure_img', to='aboutInstitut.organizationstructure')),
            ],
            options={
=======
                ('works', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='aboutInstitut.employee')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'work',
>>>>>>> origin/main
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
