# Generated by Django 5.0.1 on 2024-01-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutInstitut', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='departmentemp',
        ),
        migrations.RemoveField(
            model_name='works',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
